export default {
    music: '🎵',
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️',
    play: '▶️',
    pause: '⏸️',
    stop: '⏹️',
    skip: '⏭️',
    previous: '⏮️',
    shuffle: '🔀',
    loop: '🔁',
    volume: '🔊',
    search: '🔍',
    queue: '📜',
    duration: '⏱️',
    author: '👤',
    filter: '🎛️',
    playlist: '📋',
    add: '➕',
    remove: '➖',
    load: '📥',
    save: '💾'
};
